### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by zertosh** [ef4/fast-sourcemap-concat#10]
Hi, I forked fast-sourcemap-concat and created a version that only deals in inline sourcemaps. It only reads inline sourcemaps and only outputs inline sourcemaps. It's up on [zertosh/inline-sourcemap-concat](https://github.com/zertosh/inline-sourcemap-concat). It's part of an experiment on improving browserify build times - if it works out, then hopefully I'll get in there. Just wanted to let know :smile: Awesome job with library! I'm very happy with the results so far.
---

Maybe unfork these changes back into fast-sourcemap-concat? I've got mine passing all your tests with the same\* fixtures (I on-the-fly [convert](https://github.com/zertosh/inline-sourcemap-concat/blob/728db3efe9d306492dc69c2ef8ca49efcb3d421c/test/test.js#L196-L212) the fixtures into sources with inline sourcemaps to make them work). If this is something you're open to, then let me know how the API should work and I'd be more than happy to submit a PR.

**Comment by ef4** [comment]
I'm definitely happy to take performance improvements. Why is inline-only relevant to performance?

I wouldn't want to break existing code by removing external sourcemap support entirely. At least not until after a deprecation period.

I think the ideal API is to be generous about what inputs are accepted -- meaning we can automatically accept both inline and external sourcemaps as input. For output we can be more opinionated -- if inline is clearly better, we can make that the default. Then there can be a separate tool for converting from inline to external that people can use as a final build step, when they need to deploy that way.

As you're measuring performance, I suggest not looking only at build time, but also end-to-end time for how long it takes for the web app to launch in the browser. A potential benefit of external sourcemaps over inline is that the browser can boot the application before downloading and parsing the sourcemap.

**Comment by zertosh** [comment]
> Why is inline-only relevant to performance?

It's not so much about performance, as it is about inline maps being a browserifyism. The way the pipeline works, it only makes sense to deal in inline maps. There are [tools](https://github.com/thlorenz/exorcist) for extracting the sourcemap after the build is complete - but I'm using *-sourcemap-concat inside [core](https://github.com/substack/browser-pack) browserify.

> I think the ideal API is to be generous about what inputs are accepted 

Oh sorry - that's what I meant. I'm not suggesting to get rid of reading/writing external maps. What I would like is an option(s) that:

  1. Turns "writeMode off". That is, it makes `opts.outputFile` optional and does not create `this.stream`. Instead, it'll just collect any sources/sourcemaps it reads, and returns them when you ask. 

  2. Turns "readExternalMaps off". So `_resolveSourcemap` only returns inline source maps, skipping external ones.

These two options wouldn't be mutually exclusive. I can see others finding one or the other useful by themselves. Independent of what options are enabled, there would have to be a `comment/getComment/toComment` method that returns the inline sourcemap.

> if inline is clearly better, we can make that the default

Nah, it's ok, I'm fine with passing in opts.

> A potential benefit of external sourcemaps over inline is that the browser can boot the application before downloading and parsing the sourcemap.

That's the big win for external sourcemaps for sure, but for core browserify, can't do it :(

---

The size of the dependencies kinda sucks, but such is life - broccoli is big on promises right? Maybe  bundle the base64-vlq lib? source-map includes all of its tests in the published module x_x

Anyway, I don't want to impose myself on your project, so if you're open to these additions, I just need a bit of guidance before I put together a PR. Things like option(s) and method names and behavior. You can see what I went with in my fork: https://github.com/zertosh/inline-sourcemap-concat#var-sm--sourcemapconcatcreateopts.

Thanks again!

**Comment by stefanpenner** [comment]
Thanks for sharing.

I believe we currently support both inline and in file, as well as "passed as parameter via: https://github.com/ef4/fast-sourcemap-concat/pull/29

Anyways thanks again for sharing :)
