### ISSUE TITLE
dissect tool is broken

### ISSUE THREAD

**Issue by ef4** [ef4/fast-sourcemap-concat#11]
I noticed that `tools/dissect.js` has stopped working, probably due to https://github.com/ef4/fast-sourcemap-concat/pull/8.

**Comment by stefanpenner** [comment]
@ef4 can you share more, it appears to work for me?

**Comment by stefanpenner** [comment]
example output: https://gist.github.com/stefanpenner/723f1e169c3eb4e038840a97243cd7e9

**Comment by ef4** [comment]
I think this is probably a stale issue that was fixed around 762b96136375d988ae0c8d74d3d258c4c5a1c336.
