### ISSUE TITLE
This project appears to introduce ~221 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [ef4/fast-sourcemap-concat#23]
own files likely included by mistake:
---

 - [ ] test      66
 - [ ] tools       2

dependencies (142) may be ok, but should double check:
----

 - [ ] chalk      38
 - [ ] memory-streams      58
 - [ ] source-map      33
 - [ ] source-map-url      12

**Comment by mitchlloyd** [comment]
See #24 for related PR.
