### ISSUE TITLE
Is it possible to manually specify individual input files?

### ISSUE THREAD

**Issue by chuanqisun** [ef4/fast-sourcemap-concat#68]
Reading the documentation, it seems that
1. The user must provide a single dir as the entry point
2. All the files inside the dir will be concatenated.

In my use case, the source files are scattered in separate folders, and not all files in each folder should be included. For example:
```
output-1.js is concatenated from:
  - /dir-1/file-1.js
  - /dir-2/file-1.js
output-2.js is concatenated from:
  - /dir-1/file-2.js
  - /dir-2/file-2.js
 ```  

Do you see ways to make this possible without having to reorganizing source files?

Thanks!

**Comment by ef4** [comment]
I would suggest you compose fast-sourcemap-concat with [broccoli-funnel](https://github.com/broccolijs/broccoli-funnel) and [broccoli-merge-trees](https://github.com/broccolijs/broccoli-merge-trees).

broccoli-funnel can select the files you want to concat, and then after concat you can merge the trees back together.

**Comment by chuanqisun** [comment]
Thanks for the suggestions! I've never looked into the Ember ecosystem before. It's good to find tools that are not related to rollup or webpack :)

**Comment by ef4** [comment]
Haha, well I'm glad to help although having niche build tooling that nobody else uses is something of a sore point we are working to remedy, so you'll probably be seeing an increasing amount of rollup and webpack. 😛
