### ISSUE TITLE
`sourceRoot` not applied

### ISSUE THREAD

**Issue by jbourassa** [ef4/fast-sourcemap-concat#7]
Hi!

I tried adding `sourceRoot` to my ember-cli's Brocfile as such:

```javascript
var app = new EmberApp({
  sourcemaps: {
    enabled: true,
    extensions: ['js'],
    sourceRoot: 'http://example.com/src'
  }
);
```
only to find out that it did not prefix my sourcemap with `http://example.com/src`. I started digging and realized that:

1. `sourceRoot` is not passed to `SourceMapAwareConcat` from [ef4/broccoli-sourcemap-concat](https://github.com/ef4/broccoli-sourcemap-concat/blob/master/index.js#L16)
2. if I fixed `1`, [`SourceMap`](https://github.com/ef4/fast-sourcemap-concat/blob/master/lib/source-map.js#L354) wasn't prefixing `sourceMappingURL` with `sourceRoot`.
3. if I fixed `2` by prepending `sourceRoot` to the `mapURL`, I got an error in `broccoli-uglify-sourcemap`. My fix was to strip the `sourceRoot` from the url, at which point I kinda got it working for my app's sourcemap, but it failed for the vendor subtree.

I'm not sure where to go from there, it doesn't sound right to patch all 3 packages for fix. If you see any good way of fixing the issue within the sourcemap  flow, please let me know; I'd like to help and fix the issue rather than patching a broccoli filter to change the sourcemap url.

Cheers

**Comment by ef4** [comment]
Unfortunately I think we *do* need a broccoli filter at the very end of the pipeline to do this. 

The problem is that every intermediate stage in the pipeline needs valid local URLs in order to find the sourcemaps and transform them onward for the next stage. We really only want to add a domain name as a final deploy step.

**Comment by jbourassa** [comment]
Makes sense.

Thanks for taking the time. I'll write my own filter whenever deploying sourcemaps comes back to the top  of my todo list; and I'll make sure to open source it!
